# Generated by Django 3.2.19 on 2023-09-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='vr_game_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='vr_game_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
