# Generated by Django 3.2.19 on 2023-09-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_auto_20230911_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='VRCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('link', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='vr_cards',
            field=models.ManyToManyField(blank=True, to='inicio.VRCard'),
        ),
    ]
