# Generated by Django 3.2.19 on 2023-09-15 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_auto_20230914_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='vr_game_link',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='vr_game_title',
        ),
    ]
