# Generated by Django 3.2.19 on 2023-09-16 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_auto_20230914_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='contents',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='module',
        ),
        migrations.CreateModel(
            name='ResourceContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('link', 'Link'), ('pdf', 'PDF'), ('doc', 'Document'), ('ppt', 'PowerPoint'), ('xls', 'Excel')], max_length=10)),
                ('content', models.FileField(blank=True, null=True, upload_to='resource_content/')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='inicio.resource')),
            ],
        ),
    ]
