# Generated by Django 3.2.19 on 2023-09-16 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_auto_20230915_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='is_enabled',
        ),
    ]
