# Generated by Django 3.2.19 on 2023-09-17 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0007_tarjeta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='vr_cards',
        ),
        migrations.AlterField(
            model_name='vrcard',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='ActivityVRCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.activity')),
                ('vr_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.vrcard')),
            ],
        ),
    ]
