# Generated by Django 3.2.19 on 2023-09-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0008_auto_20230917_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='vr_cards',
            field=models.ManyToManyField(blank=True, to='inicio.VRCard'),
        ),
    ]
