# Generated by Django 3.2.19 on 2023-09-18 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0010_respuestaactividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestaactividad',
            name='archivo_respuesta',
            field=models.FileField(blank=True, null=True, upload_to='respuestas/'),
        ),
    ]
