# Generated by Django 3.2.19 on 2023-09-19 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0011_alter_respuestaactividad_archivo_respuesta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tarjeta',
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
    ]
